# Generated by Django 4.0.2 on 2022-03-10 19:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Office Admin', 'Office Admin'), ('Employee', 'Employee')], default='Employee', max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_percentage', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('role',),
            },
            managers=[
                ('postUsers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('floors_count', models.PositiveIntegerField()),
                ('building_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Remote_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_percentage', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('floor_number', models.PositiveIntegerField()),
                ('total_desks', models.PositiveIntegerField(default=0)),
                ('usable_desks', models.PositiveIntegerField(default=0)),
                ('building_id', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.CASCADE, to='api.building')),
                ('office_admin_id', models.OneToOneField(blank=True, db_column='office_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200)),
                ('office_id', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='api.office')),
            ],
        ),
        migrations.CreateModel(
            name='Desk_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('office_id', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='api.office')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_number', models.PositiveIntegerField()),
                ('is_usable', models.BooleanField(default=True)),
                ('office_id', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='api.office')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='desk_id',
            field=models.OneToOneField(blank=True, db_column='desk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.desk'),
        ),
    ]
