# Generated by Django 4.0.2 on 2022-03-03 21:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('floors_count', models.PositiveIntegerField()),
                ('building_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desk_number', models.PositiveIntegerField()),
                ('is_usable', models.BooleanField(default=True)),
                ('width_cm', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Office Admin', 'Office Admin'), ('Employee', 'Employee')], default='Employee', max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_percentage', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('is_deactivated', models.BooleanField(default=False)),
                ('desk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.desks')),
            ],
        ),
        migrations.CreateModel(
            name='Remote_Requests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('remote_percentage', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('office_address', models.CharField(max_length=200)),
                ('floor_number', models.PositiveIntegerField()),
                ('width_meters', models.FloatField()),
                ('length_meters', models.FloatField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buildings')),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.desks')),
                ('office_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_admin', to='api.users')),
                ('office_images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.users')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offices'),
        ),
        migrations.AddField(
            model_name='desks',
            name='assigned_employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AddField(
            model_name='desks',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offices'),
        ),
        migrations.CreateModel(
            name='Desk_Requests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offices')),
            ],
        ),
        migrations.AddField(
            model_name='buildings',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.offices'),
        ),
    ]
