# Generated by Django 4.0.2 on 2022-03-08 21:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('floors_count', models.PositiveIntegerField()),
                ('building_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('desk_number', models.PositiveIntegerField()),
                ('is_usable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desk_Request',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reject_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('office_address', models.CharField(max_length=200)),
                ('floor_number', models.PositiveIntegerField()),
                ('building_id', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.CASCADE, to='api.building')),
                ('desk_id', models.ForeignKey(blank=True, db_column='desk_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.desk')),
                ('img_id', models.ForeignKey(blank=True, db_column='img_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image')),
            ],
        ),
        migrations.CreateModel(
            name='Remote_Request',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('remote_percentage', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reject_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Office Admin', 'Office Admin'), ('Employee', 'Employee')], default='Employee', max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('remote_percentage', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('is_deactivated', models.BooleanField(default=False)),
                ('desk_id', models.OneToOneField(blank=True, db_column='desk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.desk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='desk_requests',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='desk_requests',
            name='office',
        ),
        migrations.RemoveField(
            model_name='desks',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='desks',
            name='office',
        ),
        migrations.RemoveField(
            model_name='images',
            name='office',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='building',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='office_admin',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='office_images',
        ),
        migrations.RemoveField(
            model_name='offices',
            name='user',
        ),
        migrations.RemoveField(
            model_name='remote_requests',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='users',
            name='desk',
        ),
        migrations.DeleteModel(
            name='Buildings',
        ),
        migrations.DeleteModel(
            name='Desk_Requests',
        ),
        migrations.DeleteModel(
            name='Desks',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Offices',
        ),
        migrations.DeleteModel(
            name='Remote_Requests',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='remote_request',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='office',
            name='office_admin',
            field=models.OneToOneField(blank=True, db_column='office_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_admin', to='api.user'),
        ),
        migrations.AddField(
            model_name='office',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='api.user'),
        ),
        migrations.AddField(
            model_name='image',
            name='office_id',
            field=models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='api.office'),
        ),
        migrations.AddField(
            model_name='desk_request',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.office'),
        ),
        migrations.AddField(
            model_name='desk_request',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='desk',
            name='office_id',
            field=models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='api.office'),
        ),
        migrations.AddField(
            model_name='desk',
            name='user_id',
            field=models.OneToOneField(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee', to='api.user'),
        ),
        migrations.AddField(
            model_name='building',
            name='office_id',
            field=models.ForeignKey(blank=True, db_column='office_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.office'),
        ),
    ]
