# Generated by Django 4.0.2 on 2022-03-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_building_desk_desk_request_image_office_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desk_request',
            old_name='office',
            new_name='office_id',
        ),
        migrations.RenameField(
            model_name='desk_request',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.RemoveField(
            model_name='building',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='desk',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='desk_id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='office',
            name='office_admin',
        ),
        migrations.RemoveField(
            model_name='office',
            name='user_id',
        ),
        migrations.AddField(
            model_name='office',
            name='office_admin_id',
            field=models.OneToOneField(blank=True, db_column='office_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='office',
            name='total_desks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='office',
            name='usable_desks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='desk_request',
            name='office_id',
            field=models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='api.office'),
        ),
    ]
