# Generated by Django 4.0.2 on 2022-03-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_office_layout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building_address',
            new_name='address',
        ),
    ]
