# Generated by Django 4.0.2 on 2022-03-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desk_id',
            field=models.OneToOneField(blank=True, db_column='desk_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.desk'),
        ),
    ]
