# Generated by Django 4.0.2 on 2022-03-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building_id',
            field=models.ForeignKey(blank=True, db_column='building_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.building'),
        ),
        migrations.AddField(
            model_name='user',
            name='office_id',
            field=models.ForeignKey(blank=True, db_column='office_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.office'),
        ),
    ]
