# Generated by Django 4.0.2 on 2022-03-14 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_building_id_user_office_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_percentage', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('request_reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('reject_reason', models.TextField(blank=True, default='Request denied.')),
                ('office_id', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='api.office')),
            ],
        ),
        migrations.RemoveField(
            model_name='remote_request',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_image',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desk_id',
        ),
        migrations.AddField(
            model_name='desk',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='img_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Desk_Request',
        ),
        migrations.DeleteModel(
            name='Remote_Request',
        ),
        migrations.DeleteModel(
            name='User_Image',
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
