# Generated by Django 4.0.2 on 2022-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_request_remove_remote_request_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='img_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
