# Generated by Django 4.0.2 on 2022-03-12 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_desk_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Office_Image',
        ),
        migrations.AlterField(
            model_name='desk_request',
            name='reject_reason',
            field=models.TextField(blank=True, default='Request denied.'),
        ),
        migrations.AlterField(
            model_name='desk_request',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='remote_request',
            name='reject_reason',
            field=models.TextField(blank=True, default='Request denied.'),
        ),
        migrations.AlterField(
            model_name='remote_request',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'None')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='remote_percentage',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='User_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200)),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
