# Generated by Django 4.0.2 on 2022-03-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_image_office_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='desk_id',
            field=models.OneToOneField(blank=True, db_column='desk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.desk'),
        ),
    ]
